package vn.edu.hcmus.student.sv19127048.lab05.DictionaryHistory;

import java.awt.Cursor;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 * vn.edu.hcmus.student.sv19127048.lab05.Dictionary.DictionaryView<br> Created by 19127048 - Nguyen
 * Duc Nam<br> Date 12/12/2021 - 11:54 AM<br> Description: JDK16<br>
 */
public class DictionaryHistoryView extends JFrame {

  /**
   * Creates new form HistoryFrame
   */
  public DictionaryHistoryView() {
    dictionaryHistoryController = new DictionaryHistoryController();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    historyPanel = new JPanel();
    historyScrollPane = new JScrollPane();
    historyTable = new JTable();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Hisotry");
    setPreferredSize(new java.awt.Dimension(321, 353));
    setResizable(false);

    historyTable.setModel(new DefaultTableModel(
        dictionaryHistoryController.getHistory(),
        new String [] {
            "Word"
        }
    ));
    historyTable.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    historyScrollPane.setViewportView(historyTable);

    GroupLayout historyPanelLayout = new GroupLayout(historyPanel);
    historyPanel.setLayout(historyPanelLayout);
    historyPanelLayout.setHorizontalGroup(
        historyPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyScrollPane, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    historyPanelLayout.setVerticalGroup(
        historyPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyScrollPane, GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
    );

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
    );

    pack();
  }// </editor-fold>

  public static void renderHistoryWindow() {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DictionaryHistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new DictionaryHistoryView().setVisible(true));
  }

  // Variables declaration - do not modify
  private JPanel historyPanel;
  private JScrollPane historyScrollPane;
  private JTable historyTable;

  private final DictionaryHistoryController dictionaryHistoryController;
  // End of variables declaration
}
