package vn.edu.hcmus.student.sv19127048.lab05.Dictionary;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Objects;
import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 * vn.edu.hcmus.student.sv19127048.lab05.Dictionary<br> Created by 19127048 - Nguyen Duc Nam<br>
 * Date 12/11/2021 - 4:42 PM<br> Description: JDK16<br>
 */


public class DictionaryView extends javax.swing.JFrame {

  /**
   * Creates new form DictionaryJFrame
   */
  public DictionaryView() {
    dictionaryController = new DictionaryController();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jTab = new JTabbedPane();
    dictionaryPanel = new JPanel();
    searchButton = new JButton();
    searchField = new JTextField();
    slangWordScrollPane = new JScrollPane();
    slangWordList = new JList<>();
    definitionScrollPane = new JScrollPane();
    definitionTable = new JTable();
    editButton = new JButton();
    deleteButton = new JButton();
    searchByComboBox = new JComboBox<>();
    addNewWordPanel = new JPanel();
    slangWordLabel = new JLabel();
    slangWordField = new JTextField();
    definitionLabel = new JLabel();
    definitionField = new JTextField();
    addSlangWordButton = new JButton();
    addDefinitionButton = new JButton();
    newSlangScrollPane = new JScrollPane();
    newSlangTable = new JTable();
    editButton1 = new JButton();
    deleteButton1 = new JButton();
    menuBar = new JMenuBar();
    fileMenu = new JMenu();
    showHistoryItem = new JMenuItem();
    restoreDictionaryItem = new JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(650, 820));

    searchButton.setText("Search");
    searchButton.addActionListener(this::searchButtonActionPerformed);

    searchField.setToolTipText("Input slang word");
    searchField.addActionListener(this::searchFieldActionPerformed);

    slangWordList.setModel(new AbstractListModel<>() {
      final String[] strings = dictionaryController.getSlangWords();

      public int getSize() {
        return strings.length;
      }

      public String getElementAt(int i) {
        return strings[i];
      }
    });
    slangWordList.addListSelectionListener(this::slangWordListValueChanged);
    slangWordScrollPane.setViewportView(slangWordList);

    definitionTable.setModel(new DefaultTableModel(
        new Object [][] {
            {"hello 1"},
            {"hello 2"},
            {"hello 3"},
            {"hello 4"}
        },
        new String [] {
            "Definition"
        }
    ));
//    definitionTable.setPreferredSize(new java.awt.Dimension(250, 64));
    definitionScrollPane.setViewportView(definitionTable);

    editButton.setText("Edit");
    editButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        editButtonActionPerformed(evt);
      }
    });

    deleteButton.setText("Delete");

    searchByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by slang", "Search by definition" }));
    searchByComboBox.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        searchByComboBoxActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout dictionaryPanelLayout = new javax.swing.GroupLayout(dictionaryPanel);
    dictionaryPanel.setLayout(dictionaryPanelLayout);
    dictionaryPanelLayout.setHorizontalGroup(
        dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dictionaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dictionaryPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dictionaryPanelLayout.createSequentialGroup()
                        .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dictionaryPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchByComboBox, 0, 165, Short.MAX_VALUE))
                            .addComponent(slangWordScrollPane)
                            .addComponent(searchField))
                        .addGap(18, 18, 18)
                        .addComponent(definitionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    dictionaryPanelLayout.setVerticalGroup(
        dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dictionaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(definitionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(dictionaryPanelLayout.createSequentialGroup()
                        .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(searchByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slangWordScrollPane)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(24, 24, 24))
    );

    jTab.addTab("Dictionary", dictionaryPanel);

    slangWordLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    slangWordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    slangWordLabel.setText("Slang word:");

    slangWordField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    slangWordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    definitionLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    definitionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    definitionLabel.setText("Definition:");

    definitionField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    definitionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    addSlangWordButton.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
    addSlangWordButton.setText("Add");
    addSlangWordButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        addSlangWordButtonActionPerformed(evt);
      }
    });

    addDefinitionButton.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
    addDefinitionButton.setText("Add");

    newSlangTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null},
            {null, null},
            {null, null},
            {null, null}
        },
        new String [] {
            "Slang word", "Definition"
        }
    ));
    newSlangScrollPane.setViewportView(newSlangTable);

    editButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    editButton1.setText("Edit");
    editButton1.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        editButton1ActionPerformed(evt);
      }
    });

    deleteButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    deleteButton1.setText("Delete");

    javax.swing.GroupLayout addNewWordPanelLayout = new javax.swing.GroupLayout(addNewWordPanel);
    addNewWordPanel.setLayout(addNewWordPanelLayout);
    addNewWordPanelLayout.setHorizontalGroup(
        addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewWordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newSlangScrollPane)
                .addContainerGap())
            .addGroup(addNewWordPanelLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(editButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewWordPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slangWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addNewWordPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(definitionLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slangWordField)
                    .addComponent(definitionField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSlangWordButton)
                    .addComponent(addDefinitionButton))
                .addGap(67, 67, 67))
    );
    addNewWordPanelLayout.setVerticalGroup(
        addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewWordPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slangWordLabel)
                    .addComponent(slangWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSlangWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definitionLabel)
                    .addComponent(definitionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDefinitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(newSlangScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton1)
                    .addComponent(editButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTab.addTab("Add new word", addNewWordPanel);

    fileMenu.setText("File");

    showHistoryItem.setText("Show history");
    showHistoryItem.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    fileMenu.add(showHistoryItem);

    restoreDictionaryItem.setText("Restore default dictionary");
    fileMenu.add(restoreDictionaryItem);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab)
                .addContainerGap())
    );

    pack();
  }// </editor-fold>

  private void editButton1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    System.out.println("edit button 1");
  }

  private void addSlangWordButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void searchByComboBoxActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void editButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void searchFieldActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void searchButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jMenuItem1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void slangWordListValueChanged(ListSelectionEvent evt) {
    // TODO add your handling code here:
    System.out.println("list value changed");
    String slangWord = slangWordList.getSelectedValue();
    if (!Objects.equals(slangWord, "")) {
      loadDefinitionsIntoTable(slangWord);
    }
  }

//  /**
//   * @param args the command line arguments
//   */
//  public static void main(String[] args) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
//      java.util.logging.Logger.getLogger(DictionaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new DictionaryView().setVisible(true);
//      }
//    });
//  }

  void loadDefinitionsIntoTable(String slangWord) {
    HashSet<String> data = dictionaryController.getDefinitionsBySlangWord(slangWord);
    int size = data.size();
    Object [][] definitions = new Object[size][1];
    int i = 0;
    for (String elt: data) {
      definitions[i][0] = elt;
      ++i;
    }
    definitionTable.setModel(new DefaultTableModel(definitions, new String [] {"Definition"}));
  }

  // Variables declaration - do not modify
  private JButton addDefinitionButton;
  private JPanel addNewWordPanel;
  private JButton addSlangWordButton;
  private JTextField definitionField;
  private JLabel definitionLabel;
  private JScrollPane definitionScrollPane;
  private JTable definitionTable;
  private JButton deleteButton;
  private JButton deleteButton1;
  private JPanel dictionaryPanel;
  private JButton editButton;
  private JButton editButton1;
  private JMenu fileMenu;
  private JMenuBar menuBar;
  private JMenuItem showHistoryItem;
  private JMenuItem restoreDictionaryItem;
  private JTabbedPane jTab;
  private JScrollPane newSlangScrollPane;
  private JTable newSlangTable;
  private JButton searchButton;
  private JComboBox<String> searchByComboBox;
  private JTextField searchField;
  private JTextField slangWordField;
  private JLabel slangWordLabel;
  private JList<String> slangWordList;
  private JScrollPane slangWordScrollPane;

  private DictionaryController dictionaryController;
  // End of variables declaration
}
