package vn.edu.hcmus.student.sv19127048.lab05.Dictionary;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.OK_OPTION;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;
import static javax.swing.SwingConstants.CENTER;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.HashSet;
import java.util.Objects;
import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import vn.edu.hcmus.student.sv19127048.lab05.DictionaryHistory.DictionaryHistoryController;
import vn.edu.hcmus.student.sv19127048.lab05.DictionaryHistory.DictionaryHistoryView;

/**
 * vn.edu.hcmus.student.sv19127048.lab05.Dictionary<br> Created by 19127048 - Nguyen Duc Nam<br>
 * Date 12/11/2021 - 4:42 PM<br> Description: JDK16<br>
 */
public class DictionaryView extends JFrame {

  /**
   * Creates new form DictionaryJFrame
   */
  public DictionaryView() {
    dictionaryController = new DictionaryController();
    dictionaryHistoryController = new DictionaryHistoryController();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  private void initComponents() {

    jTab = new JTabbedPane();
    dictionaryPanel = new JPanel();
    searchButton = new JButton();
    searchField = new JTextField();
    slangWordScrollPane = new JScrollPane();
    slangWordList = new JList<>();
    definitionScrollPane = new JScrollPane();
    definitionTable = new JTable();
    editButton = new JButton();
    deleteButton = new JButton();
    searchByComboBox = new JComboBox<>();
    addNewWordPanel = new JPanel();
    slangWordLabel = new JLabel();
    slangWordField = new JTextField();
    definitionLabel = new JLabel();
    definitionField = new JTextField();
    addSlangWordButton = new JButton();
    addDefinitionButton = new JButton();
    newSlangScrollPane = new JScrollPane();
    newSlangTable = new JTable();
    editButton1 = new JButton();
    deleteButton1 = new JButton();
    menuBar = new JMenuBar();
    fileMenu = new JMenu();
    showHistoryItem = new JMenuItem();
    restoreDictionaryItem = new JMenuItem();

    setDefaultCloseOperation(EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(650, 820));

    searchButton.setText("Search");
    searchButton.addActionListener(this::searchButtonActionPerformed);

    searchField.setToolTipText("Input slang word");
    searchField.addActionListener(this::searchFieldActionPerformed);

    slangWordList.setModel(new AbstractListModel<>() {
      final String[] strings = dictionaryController.getSlangWords();

      public int getSize() {
        return strings.length;
      }

      public String getElementAt(int i) {
        return strings[i];
      }
    });
    slangWordList.addListSelectionListener(this::slangWordListValueChanged);
    slangWordScrollPane.setViewportView(slangWordList);

    definitionTable.setModel(new DefaultTableModel(
        null,
        new String [] {
            "Definition"
        }
    ));
//    definitionTable.setPreferredSize(new java.awt.Dimension(250, 64));
    definitionScrollPane.setViewportView(definitionTable);

    editButton.setText("Edit");
    editButton.addActionListener(this::editButtonActionPerformed);

    deleteButton.setText("Delete");

    searchByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by slang", "Search by definition" }));
    searchByComboBox.addActionListener(this::searchByComboBoxActionPerformed);

    javax.swing.GroupLayout dictionaryPanelLayout = new javax.swing.GroupLayout(dictionaryPanel);
    dictionaryPanel.setLayout(dictionaryPanelLayout);
    dictionaryPanelLayout.setHorizontalGroup(
        dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dictionaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dictionaryPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dictionaryPanelLayout.createSequentialGroup()
                        .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dictionaryPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchByComboBox, 0, 165, Short.MAX_VALUE))
                            .addComponent(slangWordScrollPane)
                            .addComponent(searchField))
                        .addGap(18, 18, 18)
                        .addComponent(definitionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    dictionaryPanelLayout.setVerticalGroup(
        dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dictionaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(definitionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(dictionaryPanelLayout.createSequentialGroup()
                        .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(searchByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slangWordScrollPane)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dictionaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(24, 24, 24))
    );

    jTab.addTab("Dictionary", dictionaryPanel);

    slangWordLabel.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 24)); // NOI18N
    slangWordLabel.setHorizontalAlignment(CENTER);
    slangWordLabel.setText("Slang word:");

    slangWordField.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 24)); // NOI18N
    slangWordField.setHorizontalAlignment(CENTER);

    definitionLabel.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 24)); // NOI18N
    definitionLabel.setHorizontalAlignment(CENTER);
    definitionLabel.setText("Definition:");

    definitionField.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 24)); // NOI18N
    definitionField.setHorizontalAlignment(CENTER);

    addSlangWordButton.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 23)); // NOI18N
    addSlangWordButton.setText("Add");
    addSlangWordButton.addActionListener(this::addSlangWordButtonActionPerformed);

    addDefinitionButton.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 23)); // NOI18N
    addDefinitionButton.setText("Add");

    newSlangTable.setModel(new javax.swing.table.DefaultTableModel(
        null,
        new String [] {
            "Slang word", "Definition"
        }
    ));
    newSlangScrollPane.setViewportView(newSlangTable);

    editButton1.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18)); // NOI18N
    editButton1.setText("Edit");
    editButton1.addActionListener(this::editButton1ActionPerformed);

    deleteButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    deleteButton1.setText("Delete");

    javax.swing.GroupLayout addNewWordPanelLayout = new javax.swing.GroupLayout(addNewWordPanel);
    addNewWordPanel.setLayout(addNewWordPanelLayout);
    addNewWordPanelLayout.setHorizontalGroup(
        addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewWordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newSlangScrollPane)
                .addContainerGap())
            .addGroup(addNewWordPanelLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(editButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewWordPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slangWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addNewWordPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(definitionLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slangWordField)
                    .addComponent(definitionField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSlangWordButton)
                    .addComponent(addDefinitionButton))
                .addGap(67, 67, 67))
    );
    addNewWordPanelLayout.setVerticalGroup(
        addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewWordPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slangWordLabel)
                    .addComponent(slangWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSlangWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definitionLabel)
                    .addComponent(definitionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDefinitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(newSlangScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton1)
                    .addComponent(editButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTab.addTab("Add new word", addNewWordPanel);

    fileMenu.setText("File");

    showHistoryItem.setText("Show history");
    showHistoryItem.addActionListener(this::showHistoryItemActionPerformed);
    fileMenu.add(showHistoryItem);

    restoreDictionaryItem.setText("Restore default dictionary");
    fileMenu.add(restoreDictionaryItem);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab)
                .addContainerGap())
    );

    pack();
  }// </editor-fold>

  private void editButton1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    System.out.println("edit button 1");
  }

  /**
   * Add slang word moi vao dictionary
   * @param evt
   */
  private void addSlangWordButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    System.out.println("Slang word added");

    String newSlangWord = slangWordField.getText();
    String newDefinition = definitionField.getText();

    // Kiem tra cac truong co trong khong
    if (newSlangWord.isEmpty() || newDefinition.isEmpty()) {
      JOptionPane.showMessageDialog(
          null,
          "Slang word field or definition field is empty try again",
          "Empty field",
          ERROR_MESSAGE
      );
    } else {
      // Kiem tra slang co ton tai hay khong neu co
      // Override, duplicate
      if (dictionaryController.isSlangWordExist(newSlangWord)) {
        int state = JOptionPane.showOptionDialog(
            null,
            String.format("%s already existed, do you want to override or duplicate it",
                newSlangWord),
            "Existed slang word",
            YES_NO_CANCEL_OPTION,
            INFORMATION_MESSAGE,
            null,
            new String[]{"Override", "Duplicate", "Cancel"},
            2
        );

        switch (state) {
          // Override
          case 1 -> dictionaryController.addNewSlangWord(newSlangWord, newDefinition);
          // Duplicate
          case 2 -> dictionaryController.addNewDefinition(newSlangWord, newDefinition);
        }
      } else { // Ghi slang word moi vao dictionary
        dictionaryController.addNewSlangWord(newSlangWord, newDefinition);
      }
    }
  }

  private void searchByComboBoxActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void editButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void searchFieldActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
  }

  /**
   * Search button event handle
   * @param evt searchButton event
   */
  private void searchButtonActionPerformed(ActionEvent evt) {
    System.out.println("Search button clicked");
    // TODO add your handling code here:
    // Lay tu search trong searchField
    String searchStr = searchField.getText();
    String[] listStrings;

    // Ghi lai lich su search
    dictionaryHistoryController.writeSearchHistory(searchStr);

    // Neu khong co tu nao trong searchField render lai list goc
    if (searchStr.length() == 0) {
      listStrings = dictionaryController.getSlangWords();
    } else { // Neu co tu trong searchField render tu can search vao list
      // Search slang word theo definition
      if (Objects.equals(searchByComboBox.getSelectedItem(), "Search by definition")) {
        listStrings = dictionaryController.getSlangWordsByDefinition(searchStr);
      } else { // Search definition theo slang word
        listStrings = new String[]{searchStr};
      }
    }

    // Render list
    slangWordList.setModel(new AbstractListModel<>() {
      final String[] strings = listStrings;

      public int getSize() {
        return strings.length;
      }

      public String getElementAt(int i) {
        return strings[i];
      }
    });
  }

  private void showHistoryItemActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    DictionaryHistoryView.renderHistoryWindow();
  }

  private void slangWordListValueChanged(ListSelectionEvent evt) {
    System.out.println("List value has changed");
    // TODO add your handling code here:
    String slangWord = slangWordList.getSelectedValue();
    if (!Objects.equals(slangWord, "")) {
      loadDefinitionsIntoTable(slangWord);
    }
  }

  void loadDefinitionsIntoTable(String slangWord) {
    HashSet<String> data = dictionaryController.getDefinitionsBySlangWord(slangWord);
    if (data != null) {
      int size = data.size();
      Object [][] definitions = new Object[size][1];
      int i = 0;
      for (String elt: data) {
        definitions[i][0] = elt;
        ++i;
      }
      definitionTable.setModel(new DefaultTableModel(definitions, new String [] {"Definition"}));
    }
  }

  // Variables declaration - do not modify
  private JButton addDefinitionButton;
  private JPanel addNewWordPanel;
  private JButton addSlangWordButton;
  private JTextField definitionField;
  private JLabel definitionLabel;
  private JScrollPane definitionScrollPane;
  private JTable definitionTable;
  private JButton deleteButton;
  private JButton deleteButton1;
  private JPanel dictionaryPanel;
  private JButton editButton;
  private JButton editButton1;
  private JMenu fileMenu;
  private JMenuBar menuBar;
  private JMenuItem showHistoryItem;
  private JMenuItem restoreDictionaryItem;
  private JTabbedPane jTab;
  private JScrollPane newSlangScrollPane;
  private JTable newSlangTable;
  private JButton searchButton;
  private JComboBox<String> searchByComboBox;
  private JTextField searchField;
  private JTextField slangWordField;
  private JLabel slangWordLabel;
  private JList<String> slangWordList;
  private JScrollPane slangWordScrollPane;

  private final DictionaryController dictionaryController;
  private final DictionaryHistoryController dictionaryHistoryController;
  // End of variables declaration
}
