package vn.edu.hcmus.student.sv19127048.lab05.Game;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import vn.edu.hcmus.student.sv19127048.lab05.Dictionary.Dictionary;
import vn.edu.hcmus.student.sv19127048.lab05.Dictionary.DictionaryController;

/**
 * vn.edu.hcmus.student.sv19127048.lab05.Game<br> Created by 19127048 - Nguyen Duc Nam<br> Date
 * 12/13/2021 - 7:52 PM<br> Description: JDK16<br>
 */
public class GameView extends JFrame implements ActionListener {

  /**
   * Creates new form GameFrame
   */
  public GameView(DictionaryController dictionaryController) {
    this.dictionaryController = dictionaryController;
    initComponents();
    initGamePlay();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    slangWordLabel = new JLabel();
    answer1 = new JButton();
    answer1.addActionListener(this);

    answer2 = new JButton();
    answer2.addActionListener(this);

    answer3 = new JButton();
    answer3.addActionListener(this);

    answer4 = new JButton();
    answer4.addActionListener(this);

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Guess Game");

    slangWordLabel.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
    slangWordLabel.setHorizontalAlignment(SwingConstants.CENTER);

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(answer2, GroupLayout.PREFERRED_SIZE, 336, GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer1, GroupLayout.PREFERRED_SIZE, 336, GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer3, GroupLayout.PREFERRED_SIZE, 336, GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer4, GroupLayout.PREFERRED_SIZE, 336, GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(slangWordLabel, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(slangWordLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answer1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer2, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer3, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer4, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>

  private void initGamePlay() {
    String randomSlang = dictionaryController.getRandomSlangWord();
    String[] randomDefinition = dictionaryController.getRandomDefinition(randomSlang);

    slangWordLabel.setText(randomSlang);
    answer1.setText(randomDefinition[0]);
    answer2.setText(randomDefinition[1]);
    answer3.setText(randomDefinition[2]);
    answer4.setText(randomDefinition[3]);
  }

  /**
   * Render game window
   */
  public void renderGameWindow() {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    EventQueue.invokeLater(() -> setVisible(true));
  }

  public JButton getAnswer1() {
    return answer1;
  }

  public JButton getAnswer2() {
    return answer2;
  }

  public JButton getAnswer3() {
    return answer3;
  }

  public JButton getAnswer4() {
    return answer4;
  }

  public JLabel getSlangWordLabel() {
    return slangWordLabel;
  }

  @Override
  public void actionPerformed(ActionEvent e) {
    boolean isCorrect;

    if (e.getSource() == answer1) {
      System.out.println("Clicked answer 1");
      String definition = answer1.getText();
      isCorrect = dictionaryController.isDefinitionOfSlangCorrect(slangWordLabel.getText(), definition);

    } else if (e.getSource() == answer2) {
      System.out.println("Clicked answer 2");
      String definition = answer2.getText();
      isCorrect = dictionaryController.isDefinitionOfSlangCorrect(slangWordLabel.getText(), definition);

    } else if (e.getSource() == answer3) {
      System.out.println("Clicked answer 3");
      String definition = answer3.getText();
      isCorrect = dictionaryController.isDefinitionOfSlangCorrect(slangWordLabel.getText(), definition);

    } else {
      System.out.println("Clicked answer 4");
      String definition = answer4.getText();
      isCorrect = dictionaryController.isDefinitionOfSlangCorrect(slangWordLabel.getText(), definition);

    }

    if (isCorrect) {
      JOptionPane.showMessageDialog(
          null,
          "Correct",
          "CORRECT ANSWER",
          INFORMATION_MESSAGE
      );
    } else {
      JOptionPane.showMessageDialog(
          null,
          "Wrong, try again",
          "WRONG ANSWER",
          JOptionPane.WARNING_MESSAGE
      );
    }

    initGamePlay();
  }

  // Variables declaration - do not modify
  private JButton answer1;
  private JButton answer2;
  private JButton answer3;
  private JButton answer4;
  private JLabel slangWordLabel;

  private DictionaryController dictionaryController;
  // End of variables declaration
}
